### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-plugin-jsonc#301]
- [x] Drop support for older versions of Node.js. (<20?) #459
- [x] Drop support for older versions of ESLint. (<9?) #462
- [x] Drop support for legacy config #463 
- [x] Support for flat shareable configs. (Do we want to release it before the new version?)
- [x] ESM only #461
- [ ] Language plugin #464 
- [ ] And more?

**Comment by JounQin** [comment]
I think eslint<8 will work fot a long time.
